version: '3.7'

services:
  app:
    build: .
    image: react-node-app
    env_file: .env
    entrypoint: ./wait-for-it.sh mysql:3306 -s -t 45 -- npm
    volumes:
      - ./:/code
      - /code/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    env_file: .env
    ports:
      - 3306:3306
    expose:
      - 3306