version: '3'

services:
  app:
    network_mode: bridge
    build: .
    image: react-node-app
    env_file: ./.env
    entrypoint: ./wait-for-it.sh mysql:3306 -s -t 45 -- npm
    container_name: ${react-node-app}
    volumes:
      - ./:/code
      - /code/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    network_mode: bridge
    env_file: ./.env
    ports:
      - 3306:3306
    expose:
      - 3306